jobs:
  build:
    docker:
      - image: 9200758eda66/java:latest
        
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: 9200758eda66/java:latest
        
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
